In [1]:
import pandas as pd
import numpy as np
import requests

In [ ]:
from google.colab import files
import io
import pandas as pd
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['merge_three_first_version.csv']))

Saving merge_three_first_version.csv to merge_three_first_version.csv


/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (35,41,43,44) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
data.columns

Index(['Unnamed: 0', 'dt', 'dt_iso', 'timezone', 'city_name', 'lat', 'lon',
       'temp', 'feels_like', 'temp_min', 'temp_max', 'pressure', 'sea_level',
       'grnd_level', 'humidity', 'wind_speed', 'wind_deg', 'rain_1h',
       'rain_3h', 'snow_1h', 'snow_3h', 'clouds_all', 'weather_id',
       'weather_main', 'weather_description', 'weather_icon', 'ts', 'speed',
       'street', 'level', 'Unnamed: 0.1', 'Accident Number', 'Citation Number',
       'Citation Issued', 'Accident Date Time', 'Unit Type', 'Vehicle Type',
       'Age of At Fault Person', 'Race of At Fault Person',
       'Gender of At Fault Person', 'Ethnicity of At Fault Person',
       'Driver Action', 'Driver Contributing Factor', 'First Harmful Event',
       'Zone Sector', 'Involved Injury', 'Number Injured', 'Involved Death',
       'Number Killed', 'Motorcycle Involved', 'Motorcycle At Fault',
       'Bicycle Involved', 'Bicycle At Fault', 'Pedestrian Involved',
       'Pedestrian At Fault', 'Crash Location', 'Cit

In [ ]:
df = data.copy()

In [ ]:
# Drop these columns
df.drop(columns=['Unnamed: 0','Unnamed: 0.1', 'dt','timezone', 'city_name','rain_1h',
       'rain_3h', 'snow_1h', 'snow_3h', 'clouds_all', 'weather_id', 'feels_like', 
       'temp_min', 'temp_max','Accident Number', 'Citation Number', 'weather_description', 
       'weather_icon','Citation Issued', 'Accident Date Time', 'Unit Type', 'Vehicle Type',
       'Age of At Fault Person', 'Race of At Fault Person',
       'Gender of At Fault Person', 'Ethnicity of At Fault Person',
       'Driver Action', 'Driver Contributing Factor', 'First Harmful Event',
       'Zone Sector', 'Involved Injury', 'Number Injured', 'Involved Death',
       'Number Killed', 'Motorcycle Involved', 'Motorcycle At Fault',
       'Bicycle Involved', 'Bicycle At Fault', 'Pedestrian Involved',
       'Pedestrian At Fault','City', 'Zip Code', 'ts', 'Patrol Division', 
       'Accident Round to 30min', 'sea_level','grnd_level','Crash Location',
       'Location Point', 'Patrol Division', 'road1', 'road2', 'relevant_new',
       'road1_in', 'road2_in','lat','lon'], inplace=True)

In [ ]:
df

dt_iso    temp  pressure  humidity  wind_speed  wind_deg  \
0       2019-04-22 08:00:00  280.02      1017        81        1.34       184   
1       2019-04-22 13:00:00  279.61      1021        87        0.45         9   
2       2019-04-22 13:00:00  279.61      1021        87        0.45         9   
3       2019-04-22 13:00:00  279.61      1021        87        0.45         9   
4       2019-04-22 13:00:00  279.61      1021        87        0.45         9   
...                     ...     ...       ...       ...         ...       ...   
271013  2021-10-29 23:00:00  289.76      1019        28        0.45       239   
271014  2021-10-29 23:00:00  289.76      1019        28        0.45       239   
271015  2021-10-29 23:00:00  289.76      1019        28        0.45       239   
271016  2021-10-29 23:00:00  289.76      1019        28        0.45       239   
271017  2021-10-29 23:00:00  289.76      1019        28        0.45       239   

       weather_main     speed           street  level  crash_label  
0             Clear  8.186111    FONTAINE BLVD      2          0.0  
1            Clouds  5.347222       BANDLEY DR      2          0.0  
2            Clouds  7.350000  MESA RIDGE PKWY      3          0.0  
3            Clouds  2.116667       E OHIO AVE      3          0.0  
4            Clouds  1.897222       E OHIO AVE      4          0.0  
...             ...       ...              ...    ...          ...  
271013        Clear  1.844444    FONTAINE BLVD      4          0.0  
271014        Clear  4.372222     S NEVADA AVE      3          0.0  
271015        Clear  7.516667     S NEVADA AVE      2          0.0  
271016        Clear  4.830556     S NEVADA AVE      2          0.0  
271017        Clear  3.852778     S NEVADA AVE      3          0.0  

[271018 rows x 11 columns]

In [ ]:
# Relevant Roads
roads = ['S ACADEMY BLVD', 'SH-115','E LAS VEGAS ST', 'I-25', 'VENETUCCI BLVD', \
         'LAKE AVE', 'S NEVADA AVE', 'Bandley Dr', 'N Santa Fe Ave', \
         'FOUNTAIN MESA RD', 'E MESA RIDGE PKWY', 'MESA RIDGE PKWY', 'E OHIO AVE',\
         'FONTAINE BLVD', 'CHARTER OAK RANCH RD', 'MAGRATH AVE', 'BARKELEY AVE', \
         'WESTMEADOW DR', 'CHILES AVE', 'BROADMOOR BLUFFS DR', 'NORAD RD', 'NELSON BLVD']

In [ ]:
df['dt_iso'] = pd.to_datetime(df['dt_iso'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271018 entries, 0 to 271017
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype         
---  ------        --------------   -----         
 0   dt_iso        271018 non-null  datetime64[ns]
 1   temp          271018 non-null  float64       
 2   pressure      271018 non-null  int64         
 3   humidity      271018 non-null  int64         
 4   wind_speed    271018 non-null  float64       
 5   wind_deg      271018 non-null  int64         
 6   weather_main  271018 non-null  object        
 7   speed         271018 non-null  float64       
 8   street        271018 non-null  object        
 9   level         271018 non-null  int64         
 10  crash_label   271018 non-null  float64       
dtypes: datetime64[ns](1), float64(4), int64(4), object(2)
memory usage: 22.7+ MB


In [ ]:
from datetime import datetime as dt
df['month'] = df['dt_iso'].dt.month
df['week of the year'] = df['dt_iso'].dt.week
df['day of the week'] = df['dt_iso'].dt.weekday
df['day of the month'] = df['dt_iso'].dt.day
df['hour of the day'] = df['dt_iso'].dt.hour

<ipython-input-10-8584287f101d>:3: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  df['week of the year'] = df['dt_iso'].dt.week


In [ ]:
df['weather_main'].unique()

array(['Clear', 'Clouds', 'Drizzle', 'Rain', 'Mist', 'Snow', 'Fog',
       'Thunderstorm', 'Squall', 'Haze', 'Smoke', 'Dust'], dtype=object)

In [ ]:
df.columns

Index(['dt_iso', 'temp', 'pressure', 'humidity', 'wind_speed', 'wind_deg',
       'weather_main', 'speed', 'street', 'level', 'crash_label', 'month',
       'week of the year', 'day of the week', 'day of the month',
       'hour of the day'],
      dtype='object')

In [ ]:
X = df[['temp', 'pressure', 'humidity', 'wind_speed', 'wind_deg',
       'weather_main', 'street', 'level', 'month',
       'week of the year', 'day of the week', 'day of the month',
       'hour of the day']]

In [ ]:
Y = df['crash_label']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['weather_main'] = le.fit_transform(X['weather_main'])

<ipython-input-15-4ea6e8fa8154>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['weather_main'] = le.fit_transform(X['weather_main'])


In [ ]:
X['street'] = le.fit_transform(X['street'])

<ipython-input-16-3d4157d3d431>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['street'] = le.fit_transform(X['street'])


In [ ]:
X

temp  pressure  humidity  wind_speed  wind_deg  weather_main  \
0       280.02      1017        81        1.34       184             0   
1       279.61      1021        87        0.45         9             1   
2       279.61      1021        87        0.45         9             1   
3       279.61      1021        87        0.45         9             1   
4       279.61      1021        87        0.45         9             1   
...        ...       ...       ...         ...       ...           ...   
271013  289.76      1019        28        0.45       239             0   
271014  289.76      1019        28        0.45       239             0   
271015  289.76      1019        28        0.45       239             0   
271016  289.76      1019        28        0.45       239             0   
271017  289.76      1019        28        0.45       239             0   

        street  level  month  week of the year  day of the week  \
0            7      2      4                17                0   
1            0      2      4                17                0   
2           12      3      4                17                0   
3            6      3      4                17                0   
4            6      4      4                17                0   
...        ...    ...    ...               ...              ...   
271013       7      4     10                43                4   
271014      17      3     10                43                4   
271015      17      2     10                43                4   
271016      17      2     10                43                4   
271017      17      3     10                43                4   

        day of the month  hour of the day  
0                     22                8  
1                     22               13  
2                     22               13  
3                     22               13  
4                     22               13  
...                  ...              ...  
271013                29               23  
271014                29               23  
271015                29               23  
271016                29               23  
271017                29               23  

[271018 rows x 13 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
depth_list = [5,10,15,20,25]
f1_score_test = []
f1_score_train = []
for dp in depth_list:
  clf = DecisionTreeClassifier(random_state=0,max_depth = dp)
  clf.fit(X_train,y_train)
  ytrain_pred = clf.predict(X_train)
  ytest_pred = clf.predict(X_test)
  f1_score_test.append(f1_score(y_test, ytest_pred))
  f1_score_train.append(f1_score(y_train, ytrain_pred))

In [ ]:
f1_score_test

[0.10285220397579947,
 0.5137371731214828,
 0.7922730881185499,
 0.9410382898754991,
 0.9680239245456637]

In [ ]:
f1_score_train

[0.10584839089062333,
 0.5246412464124641,
 0.8191162029459901,
 0.9711650712117674,
 0.9991968793024323]

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, ytest_pred)

0.9680239245456637

In [ ]:
f1_score(y_train, ytrain_pred)

0.9991968793024323

In [ ]:
#from sklearn.ensemble import GradientBoostingClassifier

#clf = GradientBoostingClassifier(random_state=0, max_depth=12, n_estimators=300)
#clf.fit(X_train, y_train)

KeyboardInterrupt: ignored

In [ ]:
y_test_predict_gbm = clf.predict(X_test)
y_train_predict_gbm = clf.predict(X_train)

In [ ]:
f1_score(y_test, y_test_predict_gbm)

0.9680239245456637

In [ ]:
f1_score(y_train, y_train_predict_gbm)

0.9991968793024323

In [ ]:
#feature importances
importances = clf.feature_importances_

In [ ]:
clf.feature_names_in_

array(['temp', 'pressure', 'humidity', 'wind_speed', 'wind_deg',
       'weather_main', 'street', 'level', 'month', 'week of the year',
       'day of the week', 'day of the month', 'hour of the day'],
      dtype=object)

In [ ]:
clf.classes_

array([0., 1.])

In [ ]:
for i,v in enumerate(importances):
	print('Feature: '+clf.feature_names_in_[i]+'\t\t\tScore: '+str(v))

Feature: temp			Score: 0.1622386273081016
Feature: pressure			Score: 0.12978403001418032
Feature: humidity			Score: 0.13429663310859796
Feature: wind_speed			Score: 0.07429772033980848
Feature: wind_deg			Score: 0.1357995736926635
Feature: weather_main			Score: 0.02438566689601787
Feature: street			Score: 0.05189342078615022
Feature: level			Score: 0.00499829494040883
Feature: month			Score: 0.01180152264635529
Feature: week of the year			Score: 0.0732482453534874
Feature: day of the week			Score: 0.041202540594780214
Feature: day of the month			Score: 0.08397571076294977
Feature: hour of the day			Score: 0.07207801355649836


In [ ]:
#Using SMOTE to handle class imblance

from imblearn.over_sampling import SMOTE
from collections import Counter

In [ ]:
Counter(Y)

Counter({0.0: 260136, 1.0: 10882})

In [ ]:
# transform the dataset
oversample = SMOTE()
X, Y = oversample.fit_resample(X, Y)

In [ ]:
Counter(Y)

Counter({0.0: 260136, 1.0: 260136})

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0,max_depth = 15)
clf.fit(X_train,y_train)
ytrain_pred = clf.predict(X_train)
ytest_pred = clf.predict(X_test)

In [ ]:
f1_score(y_test, ytest_pred)

0.9616520273102395

In [ ]:
f1_score(y_train, ytrain_pred)

0.9625970064585725

In [ ]:
new_record = np.array([275,1022,85,3.34,324,0,6,2,4,17,0,22,8])

In [ ]:
new_record = new_record.reshape(1,-1)

In [ ]:
aa = clf.predict(new_record)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [ ]:
aa

array([0.])

In [ ]:
clf.predict_proba(new_record)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([[1., 0.]])