In [4]:
import pandas as pd
import numpy as np
import requests

In [5]:
data = pd.read_csv("merge_three.csv")

In [6]:
data.columns

Index(['Unnamed: 0', 'dt', 'dt_iso', 'timezone', 'city_name', 'lat', 'lon',
       'temp', 'feels_like', 'temp_min', 'temp_max', 'pressure', 'sea_level',
       'grnd_level', 'humidity', 'wind_speed', 'wind_deg', 'rain_1h',
       'rain_3h', 'snow_1h', 'snow_3h', 'clouds_all', 'weather_id',
       'weather_main', 'weather_description', 'weather_icon', 'ts', 'street',
       'level', 'Unnamed: 0.1', 'Accident Number', 'Citation Number',
       'Citation Issued', 'Accident Date Time', 'Unit Type', 'Vehicle Type',
       'Age of At Fault Person', 'Race of At Fault Person',
       'Gender of At Fault Person', 'Ethnicity of At Fault Person',
       'Driver Action', 'Driver Contributing Factor', 'First Harmful Event',
       'Zone Sector', 'Involved Injury', 'Number Injured', 'Involved Death',
       'Number Killed', 'Motorcycle Involved', 'Motorcycle At Fault',
       'Bicycle Involved', 'Bicycle At Fault', 'Pedestrian Involved',
       'Pedestrian At Fault', 'Crash Location', 'City', 'Zip 

In [7]:
df = data.copy()

In [8]:
# Drop these columns
df.drop(columns=['Unnamed: 0','Unnamed: 0.1', 'dt','timezone', 'city_name','rain_1h',
       'rain_3h', 'snow_1h', 'snow_3h', 'clouds_all', 'weather_id', 'feels_like', 
       'temp_min', 'temp_max','Accident Number', 'Citation Number', 'weather_description', 
       'weather_icon','Citation Issued', 'Accident Date Time', 'Unit Type', 'Vehicle Type',
       'Age of At Fault Person', 'Race of At Fault Person',
       'Gender of At Fault Person', 'Ethnicity of At Fault Person',
       'Driver Action', 'Driver Contributing Factor', 'First Harmful Event',
       'Zone Sector', 'Involved Injury', 'Number Injured', 'Involved Death',
       'Number Killed', 'Motorcycle Involved', 'Motorcycle At Fault',
       'Bicycle Involved', 'Bicycle At Fault', 'Pedestrian Involved',
       'Pedestrian At Fault','City', 'Zip Code', 'ts', 'Patrol Division', 
       'Accident Round to 30min', 'sea_level','grnd_level','Crash Location',
       'Location Point', 'Patrol Division', 'road1', 'road2', 'relevant_new',
       'road1_in', 'road2_in','lat','lon'], inplace=True)

In [9]:
df

dt_iso    temp  pressure  humidity  wind_speed  wind_deg  \
0      2019-04-22 08:00:00  280.02      1017        81        1.34       184   
1      2019-04-22 13:00:00  279.61      1021        87        0.45         9   
2      2019-04-22 13:00:00  279.61      1021        87        0.45         9   
3      2019-04-22 13:00:00  279.61      1021        87        0.45         9   
4      2019-04-22 13:00:00  279.61      1021        87        0.45         9   
...                    ...     ...       ...       ...         ...       ...   
44606  2021-10-29 23:00:00  289.76      1019        28        0.45       239   
44607  2021-10-29 23:00:00  289.76      1019        28        0.45       239   
44608  2021-10-29 23:00:00  289.76      1019        28        0.45       239   
44609  2021-10-29 23:00:00  289.76      1019        28        0.45       239   
44610  2021-10-29 23:00:00  289.76      1019        28        0.45       239   

      weather_main           street  level  crash_label  
0            Clear    Fontaine Blvd      2          0.0  
1           Clouds  Mesa Ridge Pkwy      3          0.0  
2           Clouds       E Ohio Ave      3          0.0  
3           Clouds     S Nevada Ave      3          0.0  
4           Clouds       E Ohio Ave      4          0.0  
...            ...              ...    ...          ...  
44606        Clear     S Nevada Ave      4          0.0  
44607        Clear     S Nevada Ave      2          0.0  
44608        Clear     S Nevada Ave      3          0.0  
44609        Clear    Fontaine Blvd      3          0.0  
44610        Clear    Fontaine Blvd      4          0.0  

[44611 rows x 10 columns]

In [1]:
new_df = df[['street', 'level']].copy()
new_df.columns = ['street', 'level']
new_df

NameError: ignored

In [74]:
new_df.groupby(['street']).mean()

level
street                        
Barkeley Ave          2.860915
Broadmoor Bluffs Dr   2.738095
Charter Oak Ranch Rd  2.983193
Chiles Ave            2.699341
E Las Vegas St        3.000000
E Ohio Ave            3.385214
Fontaine Blvd         3.069444
Fountain Mesa Rd      3.156332
Lake Ave              3.009276
Magrath Ave           3.433259
Mesa Ridge Pkwy       2.967448
Nelson Blvd           3.091623
Norad Rd              2.000000
S Academy Blvd        2.951084
S Nevada Ave          2.864466
SH-115                1.898548
Venetucci Blvd        2.913121
Westmeadow Dr         3.260163

In [10]:
# Relevant Roads
roads = ['S ACADEMY BLVD', 'SH-115','E LAS VEGAS ST', 'I-25', 'VENETUCCI BLVD', \
         'LAKE AVE', 'S NEVADA AVE', 'Bandley Dr', 'N Santa Fe Ave', \
         'FOUNTAIN MESA RD', 'E MESA RIDGE PKWY', 'MESA RIDGE PKWY', 'E OHIO AVE',\
         'FONTAINE BLVD', 'CHARTER OAK RANCH RD', 'MAGRATH AVE', 'BARKELEY AVE', \
         'WESTMEADOW DR', 'CHILES AVE', 'BROADMOOR BLUFFS DR', 'NORAD RD', 'NELSON BLVD']

In [11]:
df['dt_iso'] = pd.to_datetime(df['dt_iso'])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44611 entries, 0 to 44610
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   dt_iso        44611 non-null  datetime64[ns]
 1   temp          44611 non-null  float64       
 2   pressure      44611 non-null  int64         
 3   humidity      44611 non-null  int64         
 4   wind_speed    44611 non-null  float64       
 5   wind_deg      44611 non-null  int64         
 6   weather_main  44611 non-null  object        
 7   street        44611 non-null  object        
 8   level         44611 non-null  int64         
 9   crash_label   44611 non-null  float64       
dtypes: datetime64[ns](1), float64(3), int64(4), object(2)
memory usage: 3.4+ MB


In [13]:
from datetime import datetime as dt
df['month'] = df['dt_iso'].dt.month
df['week of the year'] = df['dt_iso'].dt.week
df['day of the week'] = df['dt_iso'].dt.weekday
df['day of the month'] = df['dt_iso'].dt.day
df['hour of the day'] = df['dt_iso'].dt.hour

<ipython-input-13-8584287f101d>:3: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  df['week of the year'] = df['dt_iso'].dt.week


In [14]:
df['weather_main'].unique()

array(['Clear', 'Clouds', 'Drizzle', 'Rain', 'Mist', 'Snow', 'Fog',
       'Thunderstorm', 'Squall', 'Haze', 'Smoke', 'Dust'], dtype=object)

In [15]:
df.columns

Index(['dt_iso', 'temp', 'pressure', 'humidity', 'wind_speed', 'wind_deg',
       'weather_main', 'street', 'level', 'crash_label', 'month',
       'week of the year', 'day of the week', 'day of the month',
       'hour of the day'],
      dtype='object')

In [16]:
df

dt_iso    temp  pressure  humidity  wind_speed  wind_deg  \
0     2019-04-22 08:00:00  280.02      1017        81        1.34       184   
1     2019-04-22 13:00:00  279.61      1021        87        0.45         9   
2     2019-04-22 13:00:00  279.61      1021        87        0.45         9   
3     2019-04-22 13:00:00  279.61      1021        87        0.45         9   
4     2019-04-22 13:00:00  279.61      1021        87        0.45         9   
...                   ...     ...       ...       ...         ...       ...   
44606 2021-10-29 23:00:00  289.76      1019        28        0.45       239   
44607 2021-10-29 23:00:00  289.76      1019        28        0.45       239   
44608 2021-10-29 23:00:00  289.76      1019        28        0.45       239   
44609 2021-10-29 23:00:00  289.76      1019        28        0.45       239   
44610 2021-10-29 23:00:00  289.76      1019        28        0.45       239   

      weather_main           street  level  crash_label  month  \
0            Clear    Fontaine Blvd      2          0.0      4   
1           Clouds  Mesa Ridge Pkwy      3          0.0      4   
2           Clouds       E Ohio Ave      3          0.0      4   
3           Clouds     S Nevada Ave      3          0.0      4   
4           Clouds       E Ohio Ave      4          0.0      4   
...            ...              ...    ...          ...    ...   
44606        Clear     S Nevada Ave      4          0.0     10   
44607        Clear     S Nevada Ave      2          0.0     10   
44608        Clear     S Nevada Ave      3          0.0     10   
44609        Clear    Fontaine Blvd      3          0.0     10   
44610        Clear    Fontaine Blvd      4          0.0     10   

       week of the year  day of the week  day of the month  hour of the day  
0                    17                0                22                8  
1                    17                0                22               13  
2                    17                0                22               13  
3                    17                0                22               13  
4                    17                0                22               13  
...                 ...              ...               ...              ...  
44606                43                4                29               23  
44607                43                4                29               23  
44608                43                4                29               23  
44609                43                4                29               23  
44610                43                4                29               23  

[44611 rows x 15 columns]

In [17]:
X = df[['temp', 'pressure', 'humidity', 'wind_speed', 'wind_deg',
       'weather_main', 'street', 'level', 'month',
       'week of the year', 'day of the week', 'day of the month',
       'hour of the day']]

In [18]:
Y = df['crash_label']

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['weather_main'] = le.fit_transform(X['weather_main'])

<ipython-input-19-4ea6e8fa8154>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['weather_main'] = le.fit_transform(X['weather_main'])


In [20]:
X['street'] = le.fit_transform(X['street'])

<ipython-input-20-3d4157d3d431>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['street'] = le.fit_transform(X['street'])


In [21]:
X

temp  pressure  humidity  wind_speed  wind_deg  weather_main  street  \
0      280.02      1017        81        1.34       184             0       6   
1      279.61      1021        87        0.45         9             1      10   
2      279.61      1021        87        0.45         9             1       5   
3      279.61      1021        87        0.45         9             1      14   
4      279.61      1021        87        0.45         9             1       5   
...       ...       ...       ...         ...       ...           ...     ...   
44606  289.76      1019        28        0.45       239             0      14   
44607  289.76      1019        28        0.45       239             0      14   
44608  289.76      1019        28        0.45       239             0      14   
44609  289.76      1019        28        0.45       239             0       6   
44610  289.76      1019        28        0.45       239             0       6   

       level  month  week of the year  day of the week  day of the month  \
0          2      4                17                0                22   
1          3      4                17                0                22   
2          3      4                17                0                22   
3          3      4                17                0                22   
4          4      4                17                0                22   
...      ...    ...               ...              ...               ...   
44606      4     10                43                4                29   
44607      2     10                43                4                29   
44608      3     10                43                4                29   
44609      3     10                43                4                29   
44610      4     10                43                4                29   

       hour of the day  
0                    8  
1                   13  
2                   13  
3                   13  
4                   13  
...                ...  
44606               23  
44607               23  
44608               23  
44609               23  
44610               23  

[44611 rows x 13 columns]

In [22]:
min(X['street'])

0

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [26]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
depth_list = [5,10,15,20,25]
f1_score_test = []
f1_score_train = []
for dp in depth_list:
  clf = DecisionTreeClassifier(random_state=0,max_depth = dp)
  clf.fit(X_train,y_train)
  ytrain_pred = clf.predict(X_train)
  ytest_pred = clf.predict(X_test)
  f1_score_test.append(f1_score(y_test, ytest_pred))
  f1_score_train.append(f1_score(y_train, ytrain_pred))

In [27]:
f1_score_test

[0.0, 0.20100502512562812, 0.39999999999999997, 0.58125, 0.6476761619190405]

In [28]:
f1_score_train

[0.0,
 0.301143583227446,
 0.6603396603396604,
 0.9014432989690722,
 0.9957446808510639]

In [29]:
from sklearn.metrics import f1_score
f1_score(y_test, ytest_pred)

0.6476761619190405

In [30]:
f1_score(y_train, ytrain_pred)

0.9957446808510639

In [31]:
# from sklearn.ensemble import GradientBoostingClassifier

# clf = GradientBoostingClassifier(random_state=0, max_depth=12, n_estimators=300)
# clf.fit(X_train, y_train)

In [32]:
y_test_predict_gbm = clf.predict(X_test)
y_train_predict_gbm = clf.predict(X_train)

In [33]:
f1_score(y_test, y_test_predict_gbm)

0.6476761619190405

In [34]:
f1_score(y_train, y_train_predict_gbm)

0.9957446808510639

In [35]:
#feature importances
importances = clf.feature_importances_

In [36]:
clf.feature_names_in_

array(['temp', 'pressure', 'humidity', 'wind_speed', 'wind_deg',
       'weather_main', 'street', 'level', 'month', 'week of the year',
       'day of the week', 'day of the month', 'hour of the day'],
      dtype=object)

In [37]:
clf.classes_

array([0., 1.])

In [38]:
for i,v in enumerate(importances):
	print('Feature: '+clf.feature_names_in_[i]+'\t\t\tScore: '+str(v))

Feature: temp			Score: 0.13978957743577744
Feature: pressure			Score: 0.10052433643838907
Feature: humidity			Score: 0.12197090830935382
Feature: wind_speed			Score: 0.06723769408875895
Feature: wind_deg			Score: 0.15629214924228374
Feature: weather_main			Score: 0.04058543530656992
Feature: street			Score: 0.0573523020842911
Feature: level			Score: 0.007141252020670914
Feature: month			Score: 0.027844312456088552
Feature: week of the year			Score: 0.061594858653473174
Feature: day of the week			Score: 0.04374658898826585
Feature: day of the month			Score: 0.07705795246883823
Feature: hour of the day			Score: 0.0988626325072392


In [39]:
#Using SMOTE to handle class imblance

from imblearn.over_sampling import SMOTE
from collections import Counter

In [40]:
Counter(Y)

Counter({0.0: 42991, 1.0: 1620})

In [41]:
# transform the dataset
oversample = SMOTE()
X, Y = oversample.fit_resample(X, Y)

In [42]:
Counter(Y)

Counter({0.0: 42991, 1.0: 42991})

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [62]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0,max_depth = 2)
clf.fit(X_train,y_train)
ytrain_pred = clf.predict(X_train)
ytest_pred = clf.predict(X_test)

In [63]:
f1_score(y_test, ytest_pred)

0.7765278200060809

In [64]:
f1_score(y_train, ytrain_pred)

0.781537718477375

In [65]:
new_record = np.array([275,1022,95,5.34,324,0,6,2,4,17,0,22,8])

In [66]:
new_record = new_record.reshape(1,-1)

In [70]:
clf.predict(new_record)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0.])

In [67]:
aa = clf.predict_proba(new_record)  

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [68]:
aa

array([[0.99716657, 0.00283343]])

In [69]:
clf.predict_proba(new_record)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([[0.99716657, 0.00283343]])

###Retrieving next 24 hours data for each feature and running the model to predict BRAG safety score.